site_name: Volition File Docs
theme:
  name: material
  palette:
    scheme: slate
    primary: black
  features:
    - navigation.indexes
#plugins:   # Temporarily disabled as this fails on GH actions
#  - privacy
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
